<a href="https://colab.research.google.com/github/evelynrodriguezc/computacion-blanda/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#¿ QUÉ ES EL PROCESAMIENTO DE LENGUAJE NATURAL O NLP ?

Es el conjunto de tecnicas de inteligencia artificial orientadas al manejo o entendimiento del lenguaje, entiendase lenguaje la forma en la que nos comunicamos los humanos , se le conce como NLP por sus siglas en ingles Natural Languaje Processing, su algoritmo mas conocido el algoritmo de textrank usado para realizar resumenes de texto automatizados.

## Aplicaciones

el NLP es usado en diversas areas, como auditorias, chatbots, traductores, resumenes automatizados, recuperacion de informacion, asistentes por voz entre muchas otras areas.

pero este tiene varios detalles de implementacion como lo pueden ser el idioma, el contexto del uso del lenguaje, o en algunos casos el coste computacional.


## Técnicas

El NLP requiere de ciertas base conocimiento en matematicas,estadistica, linguistica y computacion, para al finall legar un conjunto de pasos o algoritmos especificos usados en conjunto para el procesamiento del lenguaje, algunos de estas tecnicas son:

1. **Tokenizacion ->** Es la forma en la cual un texto se divide en nucleos textuales individuales, es decir palabras u oraciones acorde a la necesidad.

2. **Lemmatizacion ->** Es la tecnica mediante la cual un texto se lleva a su representacion mas basica del lenguaje es decir poner todos los sujetos en singular y los verbos en infitivo. 

3. **Limpieza de Stop Words ->** Es el proceso mediante el cual se quitan todas las palabras que no aportan valor al lenguaje, como lo son conectores.

# Ejemplo de tokenizacion 


In [ ]:
import nltk
from nltk.tokenize import word_tokenize,sent_tokenize
from nltk.corpus import stopwords
nltk.download('punkt')
texto_tokenizar = "hola soy un texto de prueba que,va ser tokenizado :3"
tokens = nltk.word_tokenize(texto_tokenizar)
tokens

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['hola',
 'soy',
 'un',
 'texto',
 'de',
 'prueba',
 'que',
 ',',
 'va',
 'ser',
 'tokenizado',
 ':3']

# Ejemplo de limpieza de stopword



In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
stops = set(stopwords.words("spanish"))
for token in tokens:
  if token in stops or len(token) <= 2:
    tokens.remove(token)
print(tokens)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
{'serías', 'tuvisteis', 'poco', 'seréis', 'tengas', 'estaríais', 'tenemos', 'suya', 'éramos', 'tuviera', 'seremos', 'estas', 'que', 'estos', 'hubieron', 'quien', 'mía', 'desde', 'vuestros', 'fuimos', 'tengamos', 'seas', 'hubisteis', 'les', 'nos', 'hubieras', 'sentida', 'fuéramos', 'otras', 'estuvieron', 'seamos', 'ellos', 'pero', 'mí', 'habéis', 'estuvieses', 'estuvieseis', 'estuve', 'serán', 'nosotros', 'habremos', 'ha', 'hasta', 'esta', 'antes', 'somos', 'estaría', 'sentidos', 'había', 'los', 'seré', 'estaré', 'seáis', 'más', 'eso', 'habidas', 'eras', 'ti', 'hayan', 'el', 'como', 'tenían', 'estarás', 'teníais', 'nosotras', 'sentido', 'en', 'estuvisteis', 'estado', 'estás', 'tendríais', 'nuestra', 'habrían', 'fueron', 'fuesen', 'hay', 'sus', 'donde', 'estada', 'fuerais', 'estad', 'contra', 'os', 'tanto', 'soy', 'sería', 'hube', 'vosotras', 'él', 'tenido', 'lo', 'ante'

# Machine learning en NLP
Las tecnicas de machine learning o deep learning mas usadas en en nlp suele ir orientadas a aplicaciones de resumenes , traduccion o chatbot.

En la aplicacion para resumenes se usa para casos de resumen de tipo abstracto o de construccion propia

#Ejemplo etiquetador sentimiento con Ml

### Paso 1
- importar librerias
- crear la base entrenamiento

In [1]:
# Librerías
from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

# definir documentos
docs = ['te quiero',
        'soy feliz',
        'genial!!',
        'excelente servicio',
        'wow esto es increible',
        'meh',
        'por qué naci',
        'te odio',
        'me das rabia',
        'creo que si pero no']

testdocs = ['que feliz me siento hoy',
        'tuve un dia lindo','odio existir']

# definir rótulos de clase
labels = array([1,1,1,1,1,0,0,-1,-1,-1])


## Paso 2 
- tokenizar las palabras
- normalizar los datos para su uso en la red neuronal

In [2]:

# enteros codifican los documentos
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
encoded_testdocs = [one_hot(d, vocab_size) for d in testdocs]
print(encoded_docs)
print(encoded_testdocs)

[[32, 23], [15, 26], [1], [42, 7], [27, 17, 41, 43], [18], [30, 26, 34], [32, 3], [6, 46, 11], [39, 36, 37, 2, 3]]
[[36, 26, 6, 3, 35], [12, 44, 30, 23], [3, 40]]


## Paso 3 
- preparar los datos para la red (es decir en forma matricial)

In [ ]:
# documentos pad con una longitud máxima de 4 palabras
max_length = 5
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
padded_testdocs = pad_sequences(encoded_testdocs, maxlen=max_length, padding='post')
print(padded_docs)
print(padded_testdocs)

[[36 35  0  0  0]
 [10 42  0  0  0]
 [ 9  0  0  0  0]
 [16 29  0  0  0]
 [25 33 10 22  0]
 [43  0  0  0  0]
 [34  5 25  0  0]
 [36 22  0  0  0]
 [ 5 43 21  0  0]
 [17 35  4 21 19]]
[[35 42  5 37  2]
 [26 29 26 42  0]
 [22  2  0  0  0]]


## Paso 4 
- diseñar y construir el modelo

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation='relu'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.summary()

## Paso 5 
- entrenar el modelo con los datos pruebas

In [ ]:
model.fit(padded_docs, labels, epochs=30, verbose=0)
loss, accuracy = model.evaluate(padded_docs, labels, verbose=0)
loss,accuracy

## Paso 6 
probar el modelo con los datos de prueba

In [ ]:
a = model.predict(padded_testdocs)
a

array([[0.01332596],
       [0.07693202],
       [0.        ]], dtype=float32)